### PR TITLE
Feature matches tab

### PR DESCRIPTION
**Pull request by aelittaezugbaya**

### CODE REVIEW

**Comment by noiresonn** [comment]
How should it look like?

**Comment by noiresonn** [comment]
https://development-gameder-ui-pr-8.herokuapp.com

**Comment by noiresonn** [comment]
It is always beneficial to supply the screenshots on how it works for you 🙃

**Comment by aelittaezugbaya** [comment]
I have found problem and fixed it, it should look like 
screenshot 2017-05-10 08 45 52

**Pull request merged**
